### PR TITLE
This commit fixes few minor issues for the docker build.

### PR DESCRIPTION
**Pull request by asqasq**
- Read Crail version from toplevel pom.xml
- Move Crail build directory to /home/crail
- Point CRAIL_HOME to /home/crail
- Use template core-site.xml.env file and subsitute environment variables
  to a new core-site.xml file

Close #51
Close #52

Signed-off-by: Adrian Schuepbach <asq@apache.org>

### CODE REVIEW

**Comment by PepperJo** [comment]
Can you add links to the JIRA issues in the commit message?
Looking at the CRAIL_HOME again I think we should just copy it to /crail instead of /home/crail. What do you think?

**Comment by asqasq** [comment]
Sure, I will add the links.

Ok, it is fine with me to copy to /crail instead of /home/crail. I think it does not matter as much, as long as the path is reasonably easy to use and generic (not include the version number).

I will change it to copy to /crail directly.

**Comment by PepperJo** [comment]
Great Thx!

**Comment by asqasq** [comment]
Uploaded the new version with the changes as discussed.

**Pull request closed without merging**
